[package]
name = "aoc18"
version = "0.1.0"
authors = ["Gijs van der Voort <vandervoort.gijs@gmail.com>"]

[[bin]]
name = "day_01"
path = "src/day_01.rs"

[[bin]]
name = "day_02"
path = "src/day_02.rs"

[[bin]]
name = "day_03"
path = "src/day_03.rs"

[dependencies]
regex = "1"
